[package]
name = "regmach"
version = "0.1.0"
authors = ["Derek <physci@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
sdl2_gfx = "0.24.0"
sdl2 = "0.24.0"

