[package]
name = "regmach"
version = "0.1.0"
authors = ["Derek <physci@gmail.com>"]
edition = "2018"

[dependencies]
rusttype = "0.8.2"
lyon = "0.15.3"
lyon_svg = "0.15.0"
rand = "0.7"



# [dependencies.sdl2]
# version = "0.32.0"
# default-features = false
# features = ["gfx"]

